services:
  - type: web
    name: smartbin-api
    env: python
    region: frankfurt
    plan: free
    rootDir: smartbin-api
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SMARTBIN_MODEL
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"

