name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps (backend only)
        run: |
          cd smartbin-api
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: FastAPI imports OK (skip YOLO/Torch)
        env:
          SMARTBIN_SKIP_LOAD: "1"
        run: |
          python - <<'PY'
          import fastapi, uvicorn
          print("✅ FastAPI & Uvicorn import OK")
          PY

  # ping your deployed API so the badge also reflects live health
  health-check:
    needs: smoke
    runs-on: ubuntu-latest
    env:
      API: https://smartbin-api-4ycp.onrender.com/health
    steps:
      - name: Wait for Render cold start (max ~2 min)
        run: |
          end=$((SECONDS+120))
          until curl -fsS "$API" | jq -e '.ok == true' >/dev/null; do
            if [ $SECONDS -gt $end ]; then
              echo "❌ Health never reached ok:true at $API"
              exit 1
            fi
            echo "…waiting for $API"
            sleep 6
          done
          echo "✅ Live health OK"
