name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # keep this aligned with what Render supports
          python-version: "3.11"

      - name: Install backend deps
        working-directory: smartbin-api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install requests pytest

      - name: Verify FastAPI app imports (without loading YOLO)
        env:
          SMARTBIN_SKIP_LOAD: "1"
        working-directory: smartbin-api
        run: |
          python - << 'PY'
          import fastapi
          import uvicorn
          import app
          assert hasattr(app, "app"), "FastAPI app not found"
          print("✅ FastAPI imported and app.app exists")
          PY

      - name: Smoke test live /health on Render
        env:
          API_URL: "https://smartbin-api-4ycp.onrender.com/health"
        run: |
          echo "Hitting $API_URL ..."
          python - << 'PY'
          import os, requests, sys
          url = os.environ["API_URL"]
          try:
              r = requests.get(url, timeout=5)
              print("Status:", r.status_code)
              print("Body:", r.text)
              r.raise_for_status()
              data = r.json()
              assert data.get("ok") is True, "Backend /health did not return ok:true"
              print("✅ Live /health looks good")
          except Exception as e:
              print("❌ Smoke test failed:", e)
              sys.exit(1)
          PY
